import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderLayout from "@/components/layout/wrapper/wrapper";
import Providers from "@/redux/store/provider";
import RestaurantLayout from "@/components/restaurantSidebar/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Order Food & Groceries App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/swiggy2.png",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <RestaurantLayout>
            <ProviderLayout>{children}</ProviderLayout>
          </RestaurantLayout>

        </Providers>
      </body>
    </html>
  );
}
